In [1]:
#PANDAS tRANSFORMATION
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.DataFrame({"id":[1,2,3,4],"name":["a","b","c","d"],"department":["it","ce","hr","hr"],"salary":[50000,20000,30000,40000],"bonus":[3000,4000,5000,6000]},index=[2,3,0,1])
df

   id name department  salary  bonus
2   1    a         it   50000   3000
3   2    b         ce   20000   4000
0   3    c         hr   30000   5000
1   4    d         hr   40000   6000

In [63]:
df2=pd.DataFrame({"id":[2,3,5],"salary":[20000,30000,40000],"city":["a1","a2","a3"]})
df2

   id  salary city
0   2   20000   a1
1   3   30000   a2
2   5   40000   a3

In [6]:
#APPLY()
#this method used to apply function to the data frame

df,df2

(   id name department  salary  bonus
 2   1    a         it   50000   3000
 3   2    b         ce   20000   4000
 0   3    c         hr   30000   5000
 1   4    d         hr   40000   6000,
    id  salary city
 0   2   20000   a1
 1   3   30000   a2
 2   5   40000   a3)

In [5]:
df.apply(lambda x:x.sum() if x.dtype !='object' else x,axis=0)

id                                                           10
name          2    a
3    b
0    c
1    d
Name: name, dtype:...
department    2    it
3    ce
0    hr
1    hr
Name: departme...
salary                                                   140000
bonus                                                     18000
dtype: object

In [7]:
df.apply(lambda x:x.sum() if x.dtype !='object' else x,axis=1)

   id name department  salary  bonus
2   1    a         it   50000   3000
3   2    b         ce   20000   4000
0   3    c         hr   30000   5000
1   4    d         hr   40000   6000

In [8]:
df.apply(lambda row:row["salary"]+row["bonus"],axis=1)

2    53000
3    24000
0    35000
1    46000
dtype: int64

In [9]:
#RAW=TRUE/FALSE
#raw=false mean the data input in series
#raw=True mean the data input in numpy
df[["salary",'bonus']].apply(lambda row:row["salary"]+row["bonus"],axis=1,raw=False)

2    53000
3    24000
0    35000
1    46000
dtype: int64

In [11]:
df[["salary",'bonus']].apply(lambda row:row[0]+row[1],axis=1,raw=True)

2    53000
3    24000
0    35000
1    46000
dtype: int64

In [15]:
#result_type='expand'
df[["salary",'bonus']].apply(lambda row:[row["salary"]+row["bonus"],row["salary"]-row["bonus"]],axis=1,result_type='expand')

       0      1
2  53000  47000
3  24000  16000
0  35000  25000
1  46000  34000

In [16]:
#ARGS
df["salary"].apply(lambda x,inc:x+inc,args=(100,))

2    50100
3    20100
0    30100
1    40100
Name: salary, dtype: int64

In [17]:
#astype()
#it typecast given column
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 2 to 1
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4 non-null      int64
 1   name        4 non-null      object
 2   department  4 non-null      object
 3   salary      4 non-null      int64
 4   bonus       4 non-null      int64
dtypes: int64(3), object(2)
memory usage: 192.0+ bytes

In [21]:
df["salary"]=df["salary"].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 2 to 1
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4 non-null      int64
 1   name        4 non-null      object
 2   department  4 non-null      object
 3   salary      4 non-null      float64
 4   bonus       4 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 192.0+ bytes

In [23]:
df["bonus"]=df["bonus"].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 2 to 1
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4 non-null      int64
 1   name        4 non-null      object
 2   department  4 non-null      object
 3   salary      4 non-null      float64
 4   bonus       4 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 192.0+ bytes

In [26]:
df

   id name department   salary   bonus
2   1    a         it  50000.0  3000.0
3   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0
1   4    d         hr  40000.0  6000.0

In [28]:
#replace (oldvalue.nwvalue,(inplace=true,false))
df["salary"].replace(50000.0,53000,inplace=True)

C:\Users\LJENG\AppData\Local\Temp\ipykernel_4684\3540378807.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["salary"].replace(50000.0,53000,inplace=True)

In [29]:
df

   id name department   salary   bonus
2   1    a         it  53000.0  3000.0
3   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0
1   4    d         hr  40000.0  6000.0

In [30]:
#CONCAT
pd.concat([df,df])

   id name department   salary   bonus
2   1    a         it  53000.0  3000.0
3   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0
1   4    d         hr  40000.0  6000.0
2   1    a         it  53000.0  3000.0
3   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0
1   4    d         hr  40000.0  6000.0

In [32]:
pd.concat([df,df],axis=1)

   id name department   salary   bonus  id name department   salary   bonus
2   1    a         it  53000.0  3000.0   1    a         it  53000.0  3000.0
3   2    b         ce  20000.0  4000.0   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0   3    c         hr  30000.0  5000.0
1   4    d         hr  40000.0  6000.0   4    d         hr  40000.0  6000.0

In [40]:
pd.concat([df,df],axis=1,sort=True)
pd.concat([df,df],axis=0,sort=True)

    bonus department  id name   salary
2  3000.0         it   1    a  53000.0
3  4000.0         ce   2    b  20000.0
0  5000.0         hr   3    c  30000.0
1  6000.0         hr   4    d  40000.0
2  3000.0         it   1    a  53000.0
3  4000.0         ce   2    b  20000.0
0  5000.0         hr   3    c  30000.0
1  6000.0         hr   4    d  40000.0

In [38]:
pd.concat([df,df],axis=0,sort=True,ignore_index=True)
pd.concat([df,df],axis=1,sort=True,ignore_index=True)

   0  1   2        3       4  5  6   7        8       9
0  3  c  hr  30000.0  5000.0  3  c  hr  30000.0  5000.0
1  4  d  hr  40000.0  6000.0  4  d  hr  40000.0  6000.0
2  1  a  it  53000.0  3000.0  1  a  it  53000.0  3000.0
3  2  b  ce  20000.0  4000.0  2  b  ce  20000.0  4000.0

In [49]:
#join parameter
#outer
#inner
pd.concat([df,df2],join="outer")
pd.concat([df,df2],join="inner")

pd.concat([df,df2],axis=1,join="inner")
pd.concat([df,df2],axis=0,join="inner",sort=True)

   id   salary
2   1  53000.0
3   2  20000.0
0   3  30000.0
1   4  40000.0
0   2  20000.0
1   3  30000.0
2   5  40000.0

In [53]:
#mergemerge two dat frame base on common keys\colums
#sql type operation
pd.merge(df,df2,how='inner',on="id")#common ids

   id name department   salary   bonus city
0   2    b         ce  20000.0  4000.0   a1
1   3    c         hr  30000.0  5000.0   a2

In [64]:
pd.merge(df,df2,how='left',on="id")
pd.merge(df,df2,left_on="id",right_on="id")

   id name department  salary_x   bonus  salary_y city
0   2    b         ce   20000.0  4000.0     20000   a1
1   3    c         hr   30000.0  5000.0     30000   a2

In [65]:
pd.merge(df.set_index("id"),df2.set_index("id"),left_index=True,right_index=True)

   name department  salary_x   bonus  salary_y city
id
2     b         ce   20000.0  4000.0     20000   a1
3     c         hr   30000.0  5000.0     30000   a2

In [66]:
# suffixed=()
pd.merge(df.set_index("id"),df2.set_index("id"),left_index=True,right_index=True,suffixes=("_emp","_city"))

   name department  salary_emp   bonus  salary_city city
id
2     b         ce     20000.0  4000.0        20000   a1
3     c         hr     30000.0  5000.0        30000   a2

In [67]:
#groupby
#it provide groupwise computation using custom/inbuilt function
g=df.groupby(by="department",as_index=True,sort=True)

In [68]:
df

   id name department   salary   bonus
2   1    a         it  53000.0  3000.0
3   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0
1   4    d         hr  40000.0  6000.0

In [70]:
g.groups#dictionary of coumn names as keys and index as values

{'ce': [3], 'hr': [0, 1], 'it': [2]}

In [73]:
print(g["salary"].sum())#group sum of salary
print(g["bonus"].sum())#group sum of bonus
print(g["bonus"].mean())#group sum of mean
print(g["bonus"].median())#group sum of median

department
ce    20000.0
hr    70000.0
it    53000.0
Name: salary, dtype: float64
department
ce     4000.0
hr    11000.0
it     3000.0
Name: bonus, dtype: float64
department
ce    4000.0
hr    5500.0
it    3000.0
Name: bonus, dtype: float64
department
ce    4000.0
hr    5500.0
it    3000.0
Name: bonus, dtype: float64

In [74]:
#agg method
g["salary"].agg(["min","max","sum","median","mean"])

                min      max      sum   median     mean
department
ce          20000.0  20000.0  20000.0  20000.0  20000.0
hr          30000.0  40000.0  70000.0  35000.0  35000.0
it          53000.0  53000.0  53000.0  53000.0  53000.0

In [75]:
#using with apply method
g["salary"].apply(lambda x:x.max()-x.min())

department
ce        0.0
hr    10000.0
it        0.0
Name: salary, dtype: float64

In [82]:
g.sample(1)#random sample for each group

   id name department   salary   bonus
3   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0
2   1    a         it  53000.0  3000.0

In [83]:
g.size()#num of row per group

department
ce    1
hr    2
it    1
dtype: int64

In [84]:
g.nth(0)#select first record from group

   id name department   salary   bonus
2   1    a         it  53000.0  3000.0
3   2    b         ce  20000.0  4000.0
0   3    c         hr  30000.0  5000.0

In [86]:
print(g["salary"].unique())#unique data in column
print(g["salary"].nunique())#number unique data in column
print(g["salary"].count())#num of none null data

department
ce             [20000.0]
hr    [30000.0, 40000.0]
it             [53000.0]
Name: salary, dtype: object
department
ce    1
hr    2
it    1
Name: salary, dtype: int64
department
ce    1
hr    2
it    1
Name: salary, dtype: int64